apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "h2ai.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "h2ai.labels" . | nindent 4 }}
data:
  h2ai.toml: |
    nats_url = {{ include "h2ai.natsUrl" . | quote }}
{{ .Values.config | indent 4 }}
