apiVersion: v1
kind: Service
metadata:
  name: {{ include "h2ai.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "h2ai.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "h2ai.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8080
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: 9090
