use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;

/// A stored prompt variant — the actual text plus metadata.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PromptVariant {
    pub variant_id: String, // UUID string
    pub adapter_name: String,
    pub prompt_key: String, // e.g. "system_preamble", "brainstorm_task"
    pub text: String,       // the prompt text
    pub source: PromptVariantSource,
    pub created_at: DateTime<Utc>,
    pub score: Option<f64>, // observed j_eff when this variant was active, None if not yet scored
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum PromptVariantSource {
    Seed, // original prompt from config
    Opro, // generated by OPRO
}

/// Thompson sampling arm for one prompt variant.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PromptBanditArm {
    pub variant_id: String,
    pub alpha: f64, // Beta distribution alpha (successes + prior)
    pub beta: f64,  // Beta distribution beta (failures + prior)
}

/// Per-adapter OPRO state, stored in NATS under {adapter_name}/_opro_state.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AdapterOproState {
    pub adapter_name: String,
    pub j_eff_ema: f64,
    pub n_tasks_total: u32,
    pub n_tasks_since_last_opro: u32,
    pub last_opro_started_at: Option<DateTime<Utc>>,
    pub suppress_until_n_tasks: u32,
    /// Bandit arms per prompt_key: each key maps to a list of arms (one per variant)
    pub bandit_arms: HashMap<String, Vec<PromptBanditArm>>,
}
